name: w_chat
version: 1.0.19
description: w_chat is a module to faciliate conversations with ai agents
homepage: https://github.com/michaelpszonka-wk/w_chat
publish_to: https://pub.workiva.org

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  app_intelligence:
    hosted:
      name: app_intelligence
      url: https://pub.workiva.org
    version: ^2.45.5
  async: ^2.8.2
  built_collection: ^5.1.1
  built_value: ^8.1.4
  collection: ^1.15.0
  frugal:
    hosted:
      name: frugal
      url: https://pub.workiva.org
    version: ^3.16.12
  graph_ui:
    hosted:
      name: graph_ui
      url: https://pub.workiva.org
    version: ^14.278.8
  intl: '>=0.16.1 <0.18.0'
  js: ^0.6.3
  key_binder:
    hosted:
      name: key_binder
      url: https://pub.workiva.org
    version: ^1.11.19
  language_translator_client:
    hosted:
      name: language_translator_client
      url: https://pub.workiva.org
    version: ^1.2.1
  launch_darkly:
    hosted:
      name: launch_darkly
      url: https://pub.workiva.org
    version: ^2.5.1
  licensing_api:
    hosted:
      name: licensing_api
      url: https://pub.workiva.org
    version: ^3.33.0
  licensing_frugal:
    hosted:
      name: licensing_frugal
      url: https://pub.workiva.org
    version: ^4.178.0
  messaging_sdk:
    hosted:
      name: messaging_sdk
      url: https://pub.workiva.org
    version: ^3.21.2
  meta: ^1.6.0
  opentracing: ^1.0.1
  over_react: ^4.4.1
  path: ^1.7.0
  pedantic: ^1.11.1
  quiver: '>=0.29.0+2 <4.0.0'
  quiver_hashcode: ^2.0.0
  react_material_ui:
    hosted:
      name: react_material_ui
      url: https://pub.workiva.org
    version: ^1.84.7
  redux: '>=4.0.0+3 <5.0.0'
  rxdart: '>=0.20.0 <0.22.0'
  state_machine: ^2.2.2
  synchronized: ^1.5.3+2
  thrift:
    hosted:
      name: thrift
      url: https://pub.workiva.org
    version: ^0.0.11
  user_analytics:
    hosted:
      name: user_analytics
      url: https://pub.workiva.org
    version: ^4.164.0
  w_common: '^2.0.0'
  w_flux: ^2.10.21
  w_module: ^2.0.30
  w_outline:
    hosted:
      name: w_outline
      url: https://pub.workiva.org
    version: '>=3.2.0 <4.0.0'
  w_router:
    hosted:
      name: w_router
      url: https://pub.workiva.org
    version: ^1.1.15
  w_session:
    hosted:
      name: w_session
      url: https://pub.workiva.org
    version: ^6.90.1
  w_transport: ^4.0.2
  w_virtual_components:
    hosted:
      name: w_virtual_components
      url: https://pub.workiva.org
    version: ^1.44.12
  wdesk_sdk:
    hosted:
      name: wdesk_sdk
      url: https://pub.workiva.org
    version: ^3.48.0
  web_skin:
    hosted:
      name: web_skin
      url: https://pub.workiva.org
    version: ^1.91.1
  web_skin_dart:
    hosted:
      name: web_skin_dart
      url: https://pub.workiva.org
    version: ^2.61.1
  wuri_sdk:
    hosted:
      name: wuri_sdk
      url: https://pub.workiva.org
    version: ^2.5.0
  w_intl:
    hosted:
      name: w_intl
      url: https://pub.workiva.org
    version: ^1.2.0

dev_dependencies:
  args: '>=1.6.0 <3.0.0'
  build_runner: '>=1.11.1+1 <3.0.0'
  build_test: '>=0.10.12+1 <3.0.0'
  build_web_compilers: '>=2.16.3 <4.0.0'
  built_value_generator: ^8.0.0
  dart_dev: ^3.9.0
  dart_style: '>=1.3.10 <3.0.0'
  dart_dev_workiva:
    hosted:
      name: dart_dev_workiva
      url: https://pub.workiva.org
    version: ^2.0.0
  dependency_validator: ^2.0.1
  glob: ^2.0.0
  over_react_format:
    hosted:
      url: https://pub.workiva.org
      name: over_react_format
    version: ^3.2.6
  platform_detect: '>=1.4.0 <3.0.0'
  react_testing_library: ^2.0.0
  test: ^1.16.5
  w_common_tools: ^2.0.0
workiva:
  core_checks:
    version: 1
    mode: disabled
dependency_validator:
  exclude:
    - app/**
